In [3]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [2]:
import numpy as np
import time

In [4]:
#Execution performance
size = 100_000_000

#Python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 11.240772485733032 seconds
numpy array time = 0.4192228317260742 seconds


In [7]:
#memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


In [15]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (5,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [31]:
#create
arr1 = np.zeros((2, 3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((2, 3)) #prefill
print(arr2, arr2.shape)

arr2_1 = np.ones((5)) #prefill
print(arr2_1, arr2_1.shape)

arr3 = np.full((3, 4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

#range(start, end, step)
arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [38]:
#Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) #dimensions = m x n
print(arr.size) #total elements - 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [42]:
#Operations on arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D -> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [46]:
#Indexing
# arr = np.array([1, 2, 3, 4, 5])

# print(arr[0])    #1
# print(arr[3])    #4

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1][1])    #5
print(arr[0][2])    #3

5
3


In [47]:
#Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [51]:
#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr %2 == 0])
print(arr[arr %2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [59]:
#Slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [65]:
#Copy vs View
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [82]:
#Data Types

arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([1, 2, 3.14, 4, 5])
arr2 = np.array([1, 2, 3.14, 4, 5, "prime"])
arr3 = np.array([3 + 5j])
arr4 = np.array([2 + 3j])
arr5 = np.array(["prime", {1, 2, 3, 4}, 3.14])

print(arr, arr.dtype)
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)
print(arr3 + arr4)
print(arr3 - arr4)
print(arr5, arr5.dtype)

[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3.14' '4' '5' 'prime'] <U32
[3.+5.j] complex128
[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3, 4} 3.14] object
